### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by JohannesBuchner** [OpenCode/geany-python-good-code#5]
Hi,

this plugin looks useful. Unfortunately it does not seem to build, I get: `src/python-good-code.c:29:1: error: unknown type name ‘GeanyFunctions’`.

It seems that geany has a new plugin API.
https://www.geany.org/manual/reference/howto.html
https://www.geany.org/manual/reference/legacy.html

**Comment by OpenCode** [comment]
Hi, this project is no longer maintained. It is an old project and it is software that I no longer use. I would be very happy if someone, still interested, creates a fork.
